/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtsRouteImport } from './routes/arts'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as IndiaRouteImport } from './routes/india'
import { Route as MonumentsRouteImport } from './routes/monuments'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ArtsSlugRouteImport } from './routes/arts/$slug'
import { Route as MonumentsSlugRouteImport } from './routes/monuments/$slug'
import { Route as TimelineSlugRouteImport } from './routes/timeline/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtsRoute = ArtsRouteImport.update({
  id: '/arts',
  path: '/arts',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiaRoute = IndiaRouteImport.update({
  id: '/india',
  path: '/india',
  getParentRoute: () => rootRouteImport,
} as any)
const MonumentsRoute = MonumentsRouteImport.update({
  id: '/monuments',
  path: '/monuments',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtsSlugRoute = ArtsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArtsRoute,
} as any)
const MonumentsSlugRoute = MonumentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MonumentsRoute,
} as any)
const TimelineSlugRoute = TimelineSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TimelineRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arts': typeof ArtsRouteWithChildren
  '/credits': typeof CreditsRoute
  '/india': typeof IndiaRoute
  '/monuments': typeof MonumentsRouteWithChildren
  '/timeline': typeof TimelineRouteWithChildren
  '/arts/$slug': typeof ArtsSlugRoute
  '/monuments/$slug': typeof MonumentsSlugRoute
  '/timeline/$slug': typeof TimelineSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arts': typeof ArtsRouteWithChildren
  '/credits': typeof CreditsRoute
  '/india': typeof IndiaRoute
  '/monuments': typeof MonumentsRouteWithChildren
  '/timeline': typeof TimelineRouteWithChildren
  '/arts/$slug': typeof ArtsSlugRoute
  '/monuments/$slug': typeof MonumentsSlugRoute
  '/timeline/$slug': typeof TimelineSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arts': typeof ArtsRouteWithChildren
  '/credits': typeof CreditsRoute
  '/india': typeof IndiaRoute
  '/monuments': typeof MonumentsRouteWithChildren
  '/timeline': typeof TimelineRouteWithChildren
  '/arts/$slug': typeof ArtsSlugRoute
  '/monuments/$slug': typeof MonumentsSlugRoute
  '/timeline/$slug': typeof TimelineSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arts'
    | '/credits'
    | '/india'
    | '/monuments'
    | '/timeline'
    | '/arts/$slug'
    | '/monuments/$slug'
    | '/timeline/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arts'
    | '/credits'
    | '/india'
    | '/monuments'
    | '/timeline'
    | '/arts/$slug'
    | '/monuments/$slug'
    | '/timeline/$slug'
  id:
    | '__root__'
    | '/'
    | '/arts'
    | '/credits'
    | '/india'
    | '/monuments'
    | '/timeline'
    | '/arts/$slug'
    | '/monuments/$slug'
    | '/timeline/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtsRoute: typeof ArtsRouteWithChildren
  CreditsRoute: typeof CreditsRoute
  IndiaRoute: typeof IndiaRoute
  MonumentsRoute: typeof MonumentsRouteWithChildren
  TimelineRoute: typeof TimelineRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arts': {
      id: '/arts'
      path: '/arts'
      fullPath: '/arts'
      preLoaderRoute: typeof ArtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/india': {
      id: '/india'
      path: '/india'
      fullPath: '/india'
      preLoaderRoute: typeof IndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monuments': {
      id: '/monuments'
      path: '/monuments'
      fullPath: '/monuments'
      preLoaderRoute: typeof MonumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arts/$slug': {
      id: '/arts/$slug'
      path: '/$slug'
      fullPath: '/arts/$slug'
      preLoaderRoute: typeof ArtsSlugRouteImport
      parentRoute: typeof ArtsRoute
    }
    '/monuments/$slug': {
      id: '/monuments/$slug'
      path: '/$slug'
      fullPath: '/monuments/$slug'
      preLoaderRoute: typeof MonumentsSlugRouteImport
      parentRoute: typeof MonumentsRoute
    }
    '/timeline/$slug': {
      id: '/timeline/$slug'
      path: '/$slug'
      fullPath: '/timeline/$slug'
      preLoaderRoute: typeof TimelineSlugRouteImport
      parentRoute: typeof TimelineRoute
    }
  }
}

interface ArtsRouteChildren {
  ArtsSlugRoute: typeof ArtsSlugRoute
}

const ArtsRouteChildren: ArtsRouteChildren = {
  ArtsSlugRoute: ArtsSlugRoute,
}

const ArtsRouteWithChildren = ArtsRoute._addFileChildren(ArtsRouteChildren)

interface MonumentsRouteChildren {
  MonumentsSlugRoute: typeof MonumentsSlugRoute
}

const MonumentsRouteChildren: MonumentsRouteChildren = {
  MonumentsSlugRoute: MonumentsSlugRoute,
}

const MonumentsRouteWithChildren = MonumentsRoute._addFileChildren(
  MonumentsRouteChildren,
)

interface TimelineRouteChildren {
  TimelineSlugRoute: typeof TimelineSlugRoute
}

const TimelineRouteChildren: TimelineRouteChildren = {
  TimelineSlugRoute: TimelineSlugRoute,
}

const TimelineRouteWithChildren = TimelineRoute._addFileChildren(
  TimelineRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtsRoute: ArtsRouteWithChildren,
  CreditsRoute: CreditsRoute,
  IndiaRoute: IndiaRoute,
  MonumentsRoute: MonumentsRouteWithChildren,
  TimelineRoute: TimelineRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
